eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: currency-gateway-service

  cloud:
    gateway:
      routes:
        - id: currency-calculation-service
          uri: lb://CURRENCY-CALCULATION-SERVICE/
          predicates:
            - Path=/exchange/**